### ISSUE TITLE
Traceback when running lunch -k

### ISSUE THREAD

**Issue by aalex** [sourcelibre/lunch#48]
```
lunch -k filename.py 
Unhandled Error
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/lunch-0.7.0-py3.9.egg/EGG-INFO/scripts/lunch", line 42, in <module>
    runner.run()
  File "/usr/local/lib/python3.9/dist-packages/lunch-0.7.0-py3.9.egg/lunch/runner.py", line 132, in run
    reactor.run()
  File "/usr/local/lib/python3.9/dist-packages/Twisted-21.7.0-py3.9.egg/twisted/internet/base.py", line 1318, in run
    self.mainLoop()
  File "/usr/local/lib/python3.9/dist-packages/Twisted-21.7.0-py3.9.egg/twisted/internet/base.py", line 1328, in mainLoop
    reactorBaseSelf.runUntilCurrent()
--- <exception caught here> ---
  File "/usr/local/lib/python3.9/dist-packages/Twisted-21.7.0-py3.9.egg/twisted/internet/base.py", line 994, in runUntilCurrent
    call.func(*call.args, **call.kw)
  File "/usr/local/lib/python3.9/dist-packages/lunch-0.7.0-py3.9.egg/lunch/master.py", line 648, in _kill
    pid = is_lunch_master_running(pid_file)
  File "/usr/local/lib/python3.9/dist-packages/lunch-0.7.0-py3.9.egg/lunch/master.py", line 596, in is_lunch_master_running
    if "python" in output:
builtins.TypeError: a bytes-like object is required, not 'str'
```

**Comment by aalex** [comment]
```bash
~/src/lunch/scripts/lunch --graphical ~/src/mpop/scripts/lunch_kiosk.py
```

```
There is an error in your lunch file !
Traceback (most recent call last):
  File "/home/odroid/src/lunch/lunch/runner.py", line 136, in run
    lunch_master = master.run_master(config_file,
  File "/home/odroid/src/lunch/lunch/master.py", line 858, in run_master
    pid_file = write_master_pid_file(identifier=master_identifier, directory=pid_dir)
  File "/home/odroid/src/lunch/lunch/master.py", line 620, in write_master_pid_file
    pid = is_lunch_master_running(pid_file)
  File "/home/odroid/src/lunch/lunch/master.py", line 596, in is_lunch_master_running
    if "python" in output:
TypeError: a bytes-like object is required, not 'str'
```

I think it might be when we launch it using Python 2, and not 3.
